campstone-lead/Capstone

package-lock.json, seed.js, server/api/artist.js, server/api/index.js, server/auth/google.js, server/db/models/artist.js, server/db/models/index.js
feature: seeded artist table and modified artist model
=> Artist model

src/App.tsx, src/pages/Artist/Signup/Genres.tsx, src/pages/Artist/Signup/ZipCodeForm.tsx, src/store/artist.ts
fix: get toggled buttons to work
=> Zipcode form

src/pages/Artist/Signup/Genres.tsx
=> fix: fix toggle on buttons

src/App.tsx, src/pages/Artist/Signup/ArtistType.tsx, src/store/artist.ts
feature: artist type buttons and page created
=> feature: artist type buttons and page created

src/store/artist.ts
fix: need to get artist to go into database. Getting an internal 500 error.
=> fix: need to get artist to go into database

src/pages/Artist/Signup/Genres.tsx, src/pages/Artist/Signup/ZipCodeForm.tsx, src/store/artist.ts
fix: need to fix undefined push error
=> fix: need to fix undefined push error

src/pages/Artist/Signup/ArtistType.tsx, src/pages/Artist/Signup/Genres.tsx, src/pages/Artist/Signup/PersonalInfo.tsx, src/store/artist.ts
fix: debugged undefined error but need new artist to get sent to db
=> fix: debugged undefined error but need new artist to get sent to db

src/pages/Artist/Signup/ArtistNameForm.tsx, src/pages/Artist/Signup/ArtistType.tsx, src/pages/Artist/Signup/Genres.tsx, src/pages/Artist/Signup/PersonalInfo.tsx, src/pages/Artist/Signup/ZipCodeForm.tsx, src/store/artist.ts
feature: new artist created in db!
=> feature: new artist created in db!

seed.js
feature: added seed data for venues, artists, bookers
=> feature: added seed data for venues, artists, bookers

server/api/artist.js, src/App.tsx, src/pages/Artist/Signup/ArtistBioForm.tsx, src/pages/Artist/Signup/ArtistNameForm.tsx, src/store/artist.ts
feature: artist bio form created, artist api post route modified, artist store modified.
=> feature: artist bio form created

package-lock.json, server/api/artist.js, src/App.tsx, src/pages/Artist/Signup/ArtistPassword.tsx, src/pages/Artist/Signup/PersonalInfo.tsx, src/pages/Artist/Signup/UploadPicture.tsx, src/store/artist.ts
feature: artist password added, artist store modified
=> feature: artist password added

src/pages/landingPage.tsx
fixed: added back and styled font for guest landing page.
=> fixed: styled font

src/pages/Tab1.tsx, src/pages/VenueRecommendations.tsx
feature: venue recommendations page created for artists
=> feature: venue recommendations page created for artists

src/pages/Tab1.tsx
fixed: extra ioncontent removed
=> fixed: extra ioncontent removed

seed.js
feature: added venue images to seed file
=> feature: added venue images to seed file

server/api/venues.js, src/App.tsx, src/pages/VenueSinglePage.tsx, src/store/venue.ts
in-progress: single Venue created
=> in-progress: single Venue created

src/pages/VenueSinglePage.tsx
feature: single page added. need to get connect button to work now
=> feature: single page added. need to get connect button to work now

src/pages/VenueSinglePage.tsx
Reverts campstone-lead/Capstone#98
=> Revert "feature: single page added. need to get connect button to work now"

src/pages/Tab1.tsx
feature: logo navigates to home
=> feature: logo navigates to home

src/App.tsx, src/AppImports.tsx, src/pages/booker/event/EventSinglePage.tsx
feature: single event view created. Needs connect functionality.
=> feature: single event view created. Needs connect functionality.

server/api/venues.js, src/App.tsx, src/pages/Profile.tsx, src/pages/VenueSingleComponent.tsx, src/pages/VenueSinglePage.tsx, src/pages/booker/Signup/BookerSignup2.tsx, src/pages/booker/event/add-event-form.tsx, src/pages/booker/venue/add-venue-form.tsx, src/store/booker.ts, src/store/event.ts
...fixed event and venue forms, improved user experience in entering addresses
=> Add events buttons, 

package-lock.json, seed.js
feature: events added to seed file. Need to fix events ordering issue. Events change order in DB - not sure why this is happening?
=> feature: events added to seed file. Need to fix events ordering issue

src/pages/UpdateBookerForm.tsx
feature: added css to update booker profile
=> feature: added css to update booker profile

package-lock.json, src/pages/ArtistSinglePage.tsx, src/pages/Tab1.tsx, src/pages/VenueSinglePage.tsx, src/pages/booker/event/EventSinglePage.tsx, src/pages/booker/venue/add-venue-form.tsx, src/pages/landingPage.tsx
feature: added back navigation to logo and fixed landing page typo
=> feature: added back navigation to logo and fixedlanding page typo
